- Code/Controllers/ATLConversationViewController.m
* Protecting against removing objects from an empty set.
> Preventing messages from being marked as read when app is not in the foreground

- Code/Controllers/ATLBaseConversationViewController.m
- Examples/Mocks/LYRMockContentStore.m
- README.md
* Updated outdated sample method in Readme. 
* Fixed bug which would scroll content offset of collection view to the wrong offset.
> Updating readme, fixing scrolling bug

- Code/Controllers/ATLConversationViewController.m
fixing this issue: https://github.com/layerhq/Atlas-iOS/issues/746
> fixed method that took in NSOrderedSet instead of NSSet

- Atlas.xcodeproj/project.pbxproj
- Code/Controllers/ATLBaseConversationViewController.m
- Examples/Programmatic/Images.xcassets/LaunchImage.launchimage/Contents.json
- Examples/Programmatic/ProgrammaticAppDelegate.m
- Examples/Storyboard/Atlas.storyboard
- Podfile.lock
* Removed unused .ds_store file.
* Removed storyboard.plist from compile source. 
* Added launch image.
> Fixed compiler warnings. close #790

- Code/Models/ATLMediaAttachment.h
- Code/Models/ATLMediaAttachment.m
Added posibility to modify thumbnail size of image attachment when presented in input toolbar.
> Thumbnail Size in input view

- Code/Controllers/ATLConversationViewController.h
- Code/Controllers/ATLConversationViewController.m
- Tests/ATLConversationViewControllerTest.m
Small typo in a ATLConversationViewController function.
> Change "identitifier" to "identifier".

- Code/Views/ATLMessageCollectionViewCell.m
- Code/Views/ATLMessageInputToolbar.m
message input toolbar disables send button when not displaying right button image.  fixed extra semicolon too
> message input toolbar state fix

- Code/Controllers/ATLConversationViewController.m
Using the collection view to reload cells at index paths doesn't affect the header and the footer, unfortunately. Also, there is an animation that comes with the reloading method of the collection view that may or may not be desired. This is a replacement that uses code from the `configureCollectionViewElements` function in order to target specific cells.
It could probably be optimized further if it were based on a participant identifier but this seemed to work for us.
> Change public reloading functions to reconfigure cells.

- Code/Controllers/ATLConversationViewController.m
property for the photo action sheet prevents photo selection from appearing when developers add additional action sheets
> photo action sheet

- README.md
> Corrects spelling errors

- Code/Controllers/ATLConversationViewController.h
- Code/Controllers/ATLConversationViewController.m
- Code/Views/ATLIncomingMessageCollectionViewCell.m
- Code/Views/ATLMessageCollectionViewCell.m
- Code/Views/ATLOutgoingMessageCollectionViewCell.m
See Feature Request: https://github.com/layerhq/Atlas-iOS/issues/856
> Allow display of avatar for outgoign messages (current logged in user)

- Code/Utilities/ATLMessagingUtilities.h
- Code/Utilities/ATLMessagingUtilities.m
- Code/Views/ATLMessageBubbleView.h
- Code/Views/ATLMessageBubbleView.m
- Code/Views/ATLMessageCollectionViewCell.h
- Code/Views/ATLMessageCollectionViewCell.m
- Examples/ATLSampleConversationViewController.m
- Tests/ATLMessageCollectionViewCellTest.m
Phone Numbers can be set to be highlighted. Clicking on them sends a notification.
> Phone Number Support

- Code/Controllers/ATLConversationViewController.m
@kmahal Let me know if I'm missing any pieces here.
https://github.com/layerhq/Atlas-iOS/issues/964
> Respect marksMessagesAsRead property on ATLConversationViewController

- Code/Controllers/ATLConversationViewController.m
- Code/Controllers/ATLParticipantTableViewController.m
- Code/Utilities/ATLMessagingUtilities.h
- Code/Utilities/ATLMessagingUtilities.m
- Code/Views/ATLConversationTableViewCell.m
- Code/Views/ATLMessageBubbleView.m
- Code/Views/ATLMessageInputToolbar.m
Two changes:
- fixes the invisible buttons -- images weren't loaded from the correct resources bundle.
- now using the new `LYRPushNotificationConfiguration` for the push alert text.
> Dynamic Framework Related Adjustments

- Atlas.podspec
Updating `public_header_files` entry in `Atlas.podspec`.
> Updating podspec

- Code/Utilities/ATLMediaInputStream.m
JIRA: https://layerhq.atlassian.net/browse/APPS-2127
> Dropped iOS7 support in ATLMediaInputStream

- Atlas.xcodeproj/project.pbxproj
- README.md
- Resources/Info.plist
Close #1127 
Close https://github.com/carthage/carthage/issues/1185
> Fix Carthage support

- .travis.yml
- Atlas.xcodeproj/xcshareddata/xcschemes/Programmatic.xcscheme
- Code/Controllers/ATLConversationListViewController.h
- Code/Controllers/ATLConversationViewController.h
- Code/Views/ATLMessageBubbleView.h
- Code/Views/ATLMessageCollectionViewCell.m
- Code/Views/ATLMessageInputToolbar.h
- Examples/Mocks/LYRMockContentStore.h
- Examples/Mocks/LYRMockContentStore.m
- Examples/Mocks/LYRQueryControllerMock.m
- Examples/Programmatic/ProgrammaticAppDelegate.m
- Gemfile
- Gemfile.lock
- Rakefile
- Tests/ALTAddressBarControllerTest.m
- Tests/ATLConversationListViewControllerTest.m
- Tests/ATLConversationViewControllerTest.m
- Tests/ATLMediaAttachmentTests.m
- Tests/ATLMediaStreamTests.m
- Tests/ATLMessageCollectionViewCellTest.m
- Tests/ATLMessageInputBarTest.m
This optional types are required for Swift compatibility.
There might be more out there to fix, I'm finding them one by one.
Cheers
> Fix swift support

- Code/Models/ATLConversationDataSource.m
We've merge the last APPS-2307 PR too fast, so here are the fixes that account for it.
> APPS-2307 - Partial Sync Integration Fixes

- Code/Models/ATLConversationDataSource.m
> Remove log on error with pagination

- Atlas.podspec
- CHANGELOG.md
- Podfile.lock
Bumping LayerKit version for release.
> Updating changelog, bumping LayerKit version

- CHANGELOG.md
- Code/Controllers/ATLConversationListViewController.m
Fixes a query in the `ATLMConversationListViewController`.
> APPS-2506 - Query Fix

- Examples/Mocks/LYRConversationMock.h
- Examples/Mocks/LYRConversationMock.m
- Examples/Programmatic/Info.plist
- Examples/Storyboard/Info.plist
- Examples/Storyboard/StoryboardAppDelegate.m
Example projects actually run...
> Lets not have a broken project

- CHANGELOG.md
- Code/Controllers/ATLConversationListViewController.m
> Don't filter listed conversations by participants

- Code/Controllers/ATLConversationListViewController.m
- Code/Utilities/ATLMediaInputStream.m
- Code/Views/ATLConversationCollectionViewHeader.h
- Examples/ATLSampleConversationListViewController.m
- Examples/ATLSampleConversationViewController.m
Fixes Atlas analyzer issues across each of the targets.
> Fix analyzer issues

- Code/Controllers/ATLConversationListViewController.h
> nullable avatarItemForConversation

- Code/Controllers/ATLConversationViewController.m
> Fixes timestamp overlay bug

- Code/Controllers/ATLConversationListViewController.h
- Code/Controllers/ATLConversationViewController.h
- Code/Models/ATLConversationDataSource.h
- Code/Models/ATLDataSourceChange.h
- Code/Protocols/ATLConversationPresenting.h
- Code/Protocols/ATLMessagePresenting.h
- Code/Utilities/ATLMessagingUtilities.h
- Code/Views/ATLBaseCollectionViewCell.h
- Code/Views/ATLMessageCollectionViewCell.m
- Examples/Programmatic/ProgrammaticAppDelegate.m
> Changed all `@import LayerKit` to `#import <LayerKit/LayerKit.h>`

- Code/Controllers/ATLConversationViewController.m
- Code/Views/ATLConversationCollectionViewHeader.m
> Fix timestamp when shouldDisplayUsernameForOneOtherParticipant is false

- Atlas.podspec
- CHANGELOG.md
- Code/Atlas.m
- Podfile.lock
```Atlas.podspec passed validation.```
> Release version 1.1.4

- Code/Models/ATLMediaAttachment.m
- Code/Utilities/ATLMessagingUtilities.h
- Code/Utilities/ATLMessagingUtilities.m
* Changed format of uploaded images from heic to jpeg
> Fixed format of images uploaded from iOS 11

- Code/Utilities/ATLMediaInputStream.m
- Code/Utilities/ATLMessagingUtilities.h
- Code/Utilities/ATLMessagingUtilities.m
- Code/Utilities/UIMutableUserNotificationAction+ATLHelpers.h
- Code/Utilities/UIMutableUserNotificationAction+ATLHelpers.m
> Fixed Xcode 9 warnings

- Atlas.podspec
- CHANGELOG.md
- Code/Atlas.m
- Podfile.lock
* Updated version to 1.1.5
* Updated LayerKit dependency to 0.26.13
* Updated changelog
> Release version 1.1.5
