Atlas.xcodeproj/project.pbxproj, Code/Models/ATLMediaAttachment.m, Code/Utilities/ATLMediaInputStream.m, Code/Views/ATLMessageCollectionViewCell.m, Tests/ATLMediaAttachmentTests.m, Tests/ATLMediaStreamTests.m, Tests/ATLTestUtilities.h, Tests/ATLTestUtilities.m
Fixes the crash where trying to initialize `ATLMessageCollectionViewCell` with a frame that has a `NaN` value for height.
Android sample app doesn't yet send multipart messages (with thumbnails and image size info) along with the full resolution photos.
=> APPS-1235 - Not Crashing on Messages With a Single Message Part Image.

Code/Controllers/ATLBaseConversationViewController.m, Code/Controllers/ATLConversationViewController.m, Code/Controllers/ATLTypingIndicatorViewController.m
This PR forces the Collection View to layout it's subviews before coming on screen. It prevents an awkward animation if pushing the collection view on screen without animation.
=> Forcing layout of collection view to prevent animation. Fixes #749

Code/Controllers/ATLConversationListViewController.h, Code/Controllers/ATLConversationListViewController.m
Choosing which delete buttons are visible is easily done by setting `deletionModes`.
But I found myself with the need to customize the title of the delete button, which is currently hardcoded to either "Local" or "Global".
I don't know if datasource methods are the best pattern for this feature, but they do the job and are flexible enough for any kind of usecase: different titles for each conversations/deletion modes, i18n, etc.
Implementation looks like this (Swift):
```swift
/**
Atlas - Returns a string to be displayed on the delete button.
*/
func conversationListViewController(conversationListViewController: ATLConversationListViewController!, deleteActionStringForConversation conversation: LYRConversation!, deletionMode: LYRDeletionMode) -> String! {
// Use conversation & …
```
=> Allow title & color customization of conversation delete buttons

Code/Controllers/ATLBaseConversationViewController.m
As per documentation, displaysAddressBar should default to `NO`.
The superfluous `_displaysAddressBar = YES` is now removed.
=> Fix default value for displaysAddressBar, as per documentation

Atlas.podspec, Code/Atlas.m, Code/Models/ATLConversationDataSource.m
LayerKit's `message.index` property has been replaced by `message.position`.
=> Making Atlas compatible with LayerKit v0.11.0

Code/Models/ATLMediaAttachment.m, Code/Utilities/ATLMediaInputStream.m, Code/Utilities/ATLMessagingUtilities.h, Code/Utilities/ATLMessagingUtilities.m
Added support for `image/gif` assets.
`ATLInputStream` now respects the number of source images (which is the number of frames an animated gif container might have) along with any image properties (gif speed and loop info) when it's transferring or resampling it.
=> Feature / APPS-1130 GIF Support for ATLInputStream and ATLMediaAttachment

Code/Views/ATLAvatarImageView.m
If a ```ATLParticipant``` doesn't have a ```avatarImageURL``` or an ```avatarImage```, whilst others do, then the avatar image view can behave erratically. The image will switch between nothing and something. Nil'ing the ```image``` when we have ```avatarInitials``` should fix the issue.
=> Nil the 'image' when setting the 'avatarItem' with just initials

Code/Views/ATLAvatarImageView.m
When I have a poor network connection I am seeing a lot of exceptions here, where image is nil.
=> Check fetched image prior to adding to cache

Code/Controllers/ATLConversationListViewController.h, Code/Controllers/ATLConversationListViewController.m
Changed documentation of displaysAvatarItem to NO because initialization defaulted to NO. I assume that the documentation was supposed to change and not the code because this way will more clearly mirror iOS Messages app.
=> displaysAvatarItem out of sync with documentation

Code/Models/ATLMediaAttachment.m, Code/Utilities/ATLMediaInputStream.m
This is fix for selecting images from Photo Stream on iOS 8. Asset Libarary returns nil in assetForURL to obtain it we need search through all assets from PhotoStream and select it manually.
=> Fix for iOS 8 images from Photo Stream

Code/Controllers/ATLConversationListViewController.h, Code/Controllers/ATLConversationListViewController.m
The ATLConversationListViewController doesn't currently support the use of Storyboards. It forces the table cell reuse identifier on any subclasses which break the registration set up by the storyboard. This pull request exposes this API as well as removes some other superfluous code.
=> conversation list storyboard support

Atlas.podspec, Code/Controllers/ATLConversationViewController.m, Examples/ATLSampleConversationListViewController.m, Examples/Mocks/LYRMessageMock.h, Examples/Mocks/LYRMessageMock.m, Podfile, Podfile.lock, Tests/ATLConversationListViewControllerTest.m, Tests/ATLTestInterface.m, Tests/LYRClientMockTests.m
This PR updates Atlas with the changes made in `LayerKit` v 0.13.0 that introduces the `LYRActor` object.  This object replaces the `LYRMessage` property `sentByUserID`.  `LYRActor` has properties `userID` and `name`, which allows for system messages in conversations.
=> Feature/layerkit 0.13.0

Code/Views/ATLAvatarImageView.h, Code/Views/ATLAvatarImageView.m, Code/Views/ATLConversationTableViewCell.m, Code/Views/ATLMessageCollectionViewCell.m, Code/Views/ATLParticipantTableViewCell.m
- Added a "resetView" function to ATLAvatarImageView
- Use the function in "prepareForReuse" for all of the cells that it's in
- Change the setting to nil to the label's text rather than the label itself
- Add a comparison between the image URL fetched and the current URL when we're about to set it
=> Attempt to fix avatar image reloading and reuse issues

Atlas.podspec, CHANGELOG.md, Code/Atlas.m, Code/Controllers/ATLConversationViewController.m, Podfile.lock
Fixes a crash where `-[ATLConversationViewController layerClientObjectsDidChange:]` still expects changes to be packed in an `NSDictionary`, when LayerKit v0.13.3 hands out concrete objects.
=> APPS-1725 - Crash Related to Changes not Being a Dictionary Anymore.

Code/Controllers/ATLConversationViewController.m
moving dispatch queue creation to common init instead of viewDidLoad to ensure the controller doesn't throw an exception from a nil queue during first load
=> Animation Queue Crash Fix

Code/Views/ATLMessageBubbleView.m
- Fix issue where you can repeatedly long press on a cell
- Fix issue where the menu controller points up on top of a cell if it's too close to the top/bottom edges of the scroll view's content view minus insets
- Fix issue where the menu controller doesn't show up if the cell is larger than the scroll view's content view minus insets
There is one issue outstanding: if you have the keyboard up and you long press, because we need to become the first responder, the keyboard is dismissed.
=> Fix UIMenuController quirks.

Code/Views/ATLMessageInputToolbar.m
When adding a media attachment with a custom font color and color, then deleting it the text field would revert to the old color because the first item in the attributed string was not styled.
1) Set color here so custom color continues on just as the font works
2) Apply styling to entire string including the newline, to fix the fact that when only the newline remained it would revert the setting of the textView.
=> Fix issues with custom font and color in media attachments.

Code/Controllers/ATLConversationViewController.m, Code/Views/ATLConversationCollectionViewHeader.m, Examples/Mocks/LYRClientMock.h, Examples/Mocks/LYRClientMock.m, Examples/Mocks/LYRMessageMock.h, Examples/Mocks/LYRMessageMock.m, Tests/ATLConversationViewControllerTest.m
This pull request allows the `ATLConversationViewController` to display a system message in a conversation by checking which value exists before grabbing the required string value.
=> Allow collectionview headers to display sender.name instead of defaulting to unknown user

Atlas.podspec, Code/Controllers/ATLConversationViewController.h, Code/Controllers/ATLConversationViewController.m, Podfile.lock, Tests/ATLConversationViewControllerTest.m
Added optional ATLConverstionViewController delegate method to pass delegate cells during initialization for further customization
=> ATLConversationViewController delegate for cell customization

Code/Controllers/ATLConversationViewController.m, Tests/ATLConversationViewControllerTest.m, Tests/ATLMessageInputBarTest.m
Functionality and tests for not calling `sendLocationMessage` which would then results in requesting permissions.
=> Don't call sendLocationMessage if not necessary

Code/Controllers/ATLConversationViewController.m
Gist: Make sure `self.objectChanges removeAllObjects` gets executed an keep a local copy of the array for further operations
Rare crash but affecting 500+ users so far
```
0	
CoreFoundation 0x00000001869c2530 __exceptionPreprocess + 128
1	
libobjc.A.dylib 0x00000001979440e4 objc_exception_throw + 56
2	
CoreFoundation 0x00000001869c23f0 +[NSException raise:format:arguments:] + 112
3	
Foundation 0x000000018786dc34 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 108
4	
UIKit 0x000000018b3a71c4 -[UICollectionView _endItemAnimations] + 9384
5	
UIKit 0x000000018b3b1b04 -[UICollectionView performBatchUpdates:completion:] + 328
6	
Hinge 0x000000010023a370 -[ATLConversationViewController queryControllerDidChangeContent:] (ATLConversationViewController.m:1185)
7 …
```
=> Safety in object changes

Code/Models/ATLConversationDataSource.m
From @andrewcopp 
**STR**
0) Go to a conversation with no chat
1) Type something into message bar
2) Scroll down and dismiss keyboard
3) Send message
**Expected Result**
Message should send
**Actual Result**
Message does not appear. Loading icon
**Reason**
Scrolling down calls scrollViewDidEndDragging which calls configurePaginationWindow which calls expandPaginationWindow. because we get YES for isExpandingPaginationWindow the the queryControllerDidChangeContentCall bail before it can configure the paginationWindow and the more message indicator
=> Setting expandingpaginatedwindow to NO when returning early

ATLMessageCollectionViewCellTests.m, Atlas.xcodeproj/project.pbxproj, Code/Views/ATLMessageCollectionViewCell.m, Tests/ATLMessageCollectionViewCellTest.m
This PR loads images and gifs on background threads when converting `NSdata` to `UImage` format, and then is set to the imageview on the main thread.  This will ensure smoother scrolling as there is no main thread delay as the data is converted.
=> Image and gif loading now occurs on a non main thread, and then is bought back to the main thread for the image view update

Code/Views/ATLMessageBubbleView.m
This fixes an issue in which, if you open the context menu on a message bubble, then pan the scroll by first tapping on the message bubble (rather in the empty area to the side of the messages), then dragging, the context menu will not close.
Additionally, cached location images were not being loaded properly, having no location data being set (this affected some additional functionality that I've been working on).
=> Dismiss UIMenuController on any pan, and fix location data for cached location images

Code/Utilities/ATLMessagingUtilities.h, Code/Utilities/ATLMessagingUtilities.m, Code/Views/ATLMessageBubbleView.m, Code/Views/ATLMessageInputToolbar.m
Issue was caused by setting a `UIPasteboard` object's image property when copying an image. The UIPasteBoard would drop the image's `imageOrientation` property when extracting upon paste. 
This is remedied by serializing the image data and using `setData:forPasteboardType:` to copy the image to the pasteboard.
=> Fixes bug which could cause images to paste with wrong orientation

Code/Controllers/ATLConversationViewController.m
This prevents errors being thrown when avatar items are enabled and a
message sender has a name rather than a userID (such as when a message
is sent by a platform).
=> Added a nil safety-check to shouldDisplayAvatarItemAtIndexPath

Code/Controllers/ATLConversationViewController.m
A change that makes conversation list controller take the asset of a photo rather than the `UIImage` instance.
=> APPS-2007 - Prioritize photo asset over UIImage when using image picker.

Code/Controllers/ATLBaseConversationViewController.m
this PR fixes a bug that causes the input accessory background to be black (window color) when presenting the `ATLConversationViewController` on screen.
=> fixes ios9 window bug

Code/Controllers/ATLConversationViewController.m
fixes #978
Issue: tap left accessory button while keyboard is visible, Alertsheet appears behind keyboard.
=> dismiss keyboard when left button tapped

Code/Controllers/ATLBaseConversationViewController.m
When the conversation view is in a popover and the keyboard is toggled, the conversation view's insets don't need to be adjusted because the popover moves to make room for the keyboard. I'm not exactly sure if this is the right solution, but this is what we implemented, so I figured I'd share it with you and let you decide.
=> Fix Conversation View's insets in popover

Code/Views/ATLMessageBubbleView.m
This includes four changes that generally improve the experience of long-pressing on message bubbles.
1. When setting custom menu items on a ATLMessageBubbleView (via `conversationViewController:configureCell:forMessage:`), they are now properly cleared from the global UIMenuController after the long-press. This avoids the following scenario:
Message bubble with extra menu option:
Then long-press in the text input field:
2. When you long press on a message bubble, and the menu comes up, and then you try panning (without ever lifting your finger from the screen), the scroll position is now locked until you lift your finger from the screen. This replicates the Apple Messenger behaviour.
3. If the message bubble long-press menu items are set to nil or an empty array (again, using …
=> Improved long-press behaviour on ATLMessageBubbleView

Code/Controllers/ATLBaseConversationViewController.m
This PR fixes as duplicate keyboard dismissal seen on ios9 when resigning first responder on `viewWillDisappear:`
=> Added ios9 fix for duplicate keyboard dismissal

Code/Views/ATLMessageInputToolbar.h, Code/Views/ATLMessageInputToolbar.m, Tests/ATLMessageInputBarTest.m
Makes the right accessory button title configurable, and resizes the textinput view according to the new text.
=> Added ATLMessageInputToolbar right button title property

Code/Views/ATLMessageBubbleView.h, Code/Views/ATLMessageBubbleView.m, Code/Views/ATLMessageCollectionViewCell.m
The issue was the way how auto layout engine tries to calculate the constraints using `NSLayoutRelationLessThanOrEqual` by doing multiple passes of sizing in order to satisfy a constraint (it starts with a 2-pass approach, and if the value still changes the second time, it does another 2-pass attempt). And while it does this, it calculates the constraints of the whole layout graph (since our layout hierarchy does not break at any point, it goes from the cell's label all the way up to the UIWindow).
I eliminated the constraint that would cause this guess the number approach and manually size the constraint based on the calculated text size.
=> APPS-2109 - Slow Scrolling Performance

Code/Views/ATLMessageInputToolbar.m
This error is not immediately obvious since the superview's frame.origin.x is the same as the containerViewController view's frame.origin.x. But this calculation should be done relative to the superview, since this is the coordinate system the containerViewController's frame is relative to.
=> ATLMessageInputToolbar call convertRect:toView: from superview

Code/Controllers/ATLConversationListViewController.h
The ATLConversationListViewController queryController property is needed to get a conversation at a specific index in the table view, such as the currently selected table view cell's index. In order to get this conversation in subclassed implementations of ATLConversationListViewController, the property needs readonly access in the header.
=> ATLConversationListViewController queryController property accessible to subclass

CHANGELOG.md, Podfile.lock, Resources/Info.plist
* Fixes an issue which prevented application archives from being submitted to the app store. The issue was caused by and unnecessary key in the `Resources/info.plist` file.
=> Removing executable keys from Resources info.plist

Code/Controllers/ATLConversationListViewController.m, Tests/ATLConversationListViewControllerTest.m
This PR fixes an issue with the tableview dequeueing a cell that hasn't been registered.
=> Fixing query controller execution issue

Code/Utilities/ATLMessagingUtilities.m, Tests/ATLConversationViewControllerTest.m
This PR fixes an issue where `[messagePart data]` returned `nil` for text message parts.  The default `ATLMessagePartsForMediaAttachments` function uses `inputStream` values which internally return `nil` initially.
=> Fixed bug which caused text message part data to be nil when checked on message did send delegate

Code/Controllers/ATLAddressBarViewController.h, Code/Controllers/ATLAddressBarViewController.m, Code/Views/ATLParticipantTableViewCell.h, Code/Views/ATLParticipantTableViewCell.m
@kmahal This allows avatars to be shown in the address bar view controller. However, it changes the look of the address bar view controller since I am reusing ATLParticipantTableViewCells, so I wanted to get your advice on whether or not this is the best path to go down.
=> Allow avatars to be shown in the ATLAddressBarViewController

Code/Views/ATLMessageInputToolbar.m
This PR aligns the right button text when disabled and enabled, as well as checks the right width if the right button image is not used.
=> Fixes padding issue

Code/Controllers/ATLConversationViewController.m, Code/Models/ATLConversationDataSource.h, Code/Models/ATLConversationDataSource.m
* This PR removes the `expandingPaginationWindow` property from `ATLConversationDataSource`. The property is no longer relevant as updates reported by setting the pagination window on an `LYRQueryController` are no longer synchronous.
* Moved logic to track whether or not the query controller is updating its pagination window to the `ATLConversationViewController`. 
We should discuss adding a `isExpandingPaginationWindow` property to `LYRQueryController`, but for now, this will do.
=> Removing isExpandingPaginationWindow bool from datasource

Resources/Info.plist
* Removing executable key from info.plist to fix cocoapods builds.
=> Removing executable key from info plist

CHANGELOG.md, Code/Models/ATLConversationDataSource.m
Caused by an unsigned integer overflow in ATLConversationDataSource.
=> APPS-2307 - Endless Spinner Fix

Code/Controllers/ATLConversationViewController.m
* Partial sync caused this bug to pop up. When you set a new conversation that has historical content, it could throw off the logic used to display the spinner. This pr removes the edge case.
=> Tiny fix for ensuring spinner is removed when setting conversation

Code/Controllers/ATLConversationListViewController.m
After fixing #1139 I found that using Xcode 7.3 Altlas still won't build using carthage:
```objc
ATLConversationListViewController.m:330:114: error: incompatible pointer types sending 'NSArray<NSNumber *> *' to parameter of type 'NSArray<UITableViewRowAction *> * _Nonnull' [-Werror,-Wincompatible-pointer-types]
NSArray *customActions = [self.dataSource conversationListViewController:self rowActionsForDeletionModes:self.deletionModes];
^~~~~~~~~~~~~~~~~~
In file included from […]/Atlas-iOS/Code/Controllers/ATLConversationListViewController.m:22:
[…]/Atlas-iOS/Code/Controllers/ATLConversationListViewController.h:130:176: note: passing argument to parameter 'deletionModes' here
- (NSArray *)conversationListViewController:(ATLConversationListViewController *)conversationListViewController …
```
=> Incorrect deletionModes type

Code/Views/ATLMessageBubbleView.m, Code/Views/ATLMessageCollectionViewCell.m
The NSDataDetector was missing the phone number type which prevents to visually identify phone numbers in chat messages(with color and underscore) and it was also preventing the gesture recognizer to trigger the proper action, upon phone number type notification.
=> Adds phone numbers recognizer for chat message (for real 😀 )

Atlas.podspec
As all imports assume that the "Code" directory is recursively searched for headers, I'd encourage to not specify a `header_mappings_dir` as this will conserve the directory structure in the header folder within the framework. While a target setup like that itself still compiles fine that causes that the imports of the public headers can't be resolved by the compiler frontend when importing the module as these imports assume a flattened out structure or headers being recursively searched. The latter would need to happen within the framework to avoid Clang complaining about "include of non-modular header inside framework module". That would be generally possible, but isn't implemented by CocoaPods so far.
=> [Podspec] Remove header_mappings_dir

Code/Controllers/ATLAddressBarViewController.h, Code/Controllers/ATLAddressBarViewController.m
Added ability to add custom cells for ATLAddresBarViewController. The default cell is ATLParticipantTableViewCell and all the default values are the same.
=> Custom cells for ATLAddresBarViewController.

README.md
There is a strange/unnecessary character. You could see the diff preview for more. :)
=> Fix a mistake in read me

Atlas.xcodeproj/project.pbxproj, Podfile.lock
There are currently two problems when integrating the library with CocoaPods, this Pull Request introduces a couple of changes that solve the issue.
* The first problem is that the `LayerKit.framework` file that is included in the `Atlas` target dependencies is pointing to a non-existing directory. Even after a `carthage update` and a `pod install` the location of the framework is different from the dependency target path.
* Corrected the `LayerKit.framework` path in the target dependencies to point to the `LayerKit.framework` file that is imported by CocoaPods. This means that, after a `pod install` the project builds without any issues.
* The second problem is that the `Atlas.podspec` specifies a `LayerKit` dependency for versions `0.21.0` or higher. However, the current version of the …
=> Resolve compiler errors when integrating library with CocoaPods

Atlas.podspec, CHANGELOG.md, Code/Controllers/ATLConversationViewController.m, Code/Utilities/ATLMessagingUtilities.m
A few breaking API changes have been introduced in LayerKit v0.22.0 and we need to update the all the affected references in Atlas.
=> APPS-2490 - Updated code to support the new LayerKit API changes.

CHANGELOG.md, Code/Controllers/ATLConversationListViewController.m
With the new `LYRQueryController` behavior, conversation list view controller could crash when de-authenticating the client or when transitioning from one view controller to another.
=> APPS-2560 - Query Controller Fix

Code/Controllers/ATLBaseConversationViewController.m
This addresses #1266 by bumping the minimum required version to `@"9.0"`.
I also took the liberty to replace the macro with an inline function, since they benefit from being checked by the compiler.
=> Bump version check for content flashing workaround

Code/Controllers/ATLConversationViewController.m
This change fixes issue #1116 which happens with LayerKit v0.21.1 and Atlas v1.0.23.
When ATLConversationViewController is dismissed, conversationDataSource is set to nil but the query controller delegate is still bound to the controller. If a new message is received for the related conversation, conversationDataSource.queryController triggers the delegate to update the collection view, but numberOfSectionsInCollectionView in ATLConversationViewController returns 0+1, which causes the inconsistency.
The fix is unsetting the delegate so the query controller does not track changes when conversation view controller is dismissed. Updating the setConversation method in ATLConversationViewController fixes the issue.
=> Fix for NSInternalInconsistencyException when conversation is updated

Code/Controllers/ATLParticipantTableViewController.m, Code/Models/ATLParticipantTableDataSet.h, Code/Models/ATLParticipantTableDataSet.m
Fix for APPS-2470. ATLParticipantTableDataSet is now "mutable". ATLParticipantTableViewController now observes LYRClient changes to identity objects and channels participant changes to the ATLParticipantTableDataSet, which in turn updates the section info which drives the table view.
=> Observe object changes to identities in the participant list

Code/Controllers/ATLConversationListViewController.m
Adds pagination (using LYRQueryController.paginationWindow, set to 30). Pulls in the next page of conversations when scrolled close to the bottom of the table view. Activity spinner placed in table view footer while there are additional pages of conversations.
NOTE: There is another branch (APPS-2524-conversation-pagination) that attempts the same functionality. I created by own branch (signified with my initials MAK in the name) instead of using that one.
=> APPS-2524 Conversation Pagination (MAK)

Code/Views/ATLBaseCollectionViewCell.m
When calling -configureCellForType, the layout can incorrectly apply a near full width avatarImageView because the (12) padding on the left/right depending on the previous type was never removed. This PR persists and removes that constraint when the cellType is dynamically changed. This was not noticed if the cellType was never changed as is the case using ATLIncomingMessageCollectionViewCell / Outcoming as they are only set once.
This is what happened previously:
Notice the 12-avatar-12 constraints which were left
=> fixes alignment constraint never removed so avatar is almost full width

Code/Controllers/ATLConversationViewController.m
Avoid doing it in `loadView` so it can be overridden (for instance to set a `ATLConversationView` subclass as `self.view`) or instantiated in IB.
From Apple:
> If you want to perform any additional initialization of your views, do so in the `viewDidLoad` method.
=> ATLConversationViewController: Initialize `collectionView` in `viewDidLoad`

Code/Views/ATLAvatarImageView.m
When setting the image for the the same remoteImageURL the avatar view would set its alpha to 0.0 and then animate the image again, which looks weird then using the exact same image.
=> Prevent ATLAvatarImageView from “flashing” when setting the same remoteImageURL’s image

Code/Controllers/ATLBaseConversationViewController.m, Code/Controllers/ATLConversationViewController.m, Code/Utilities/UICollectionView+ATLHelpers.h, Code/Utilities/UICollectionView+ATLHelpers.m, Code/Utilities/UIView+ATLHelpers.h, Code/Utilities/UIView+ATLHelpers.m, Code/Views/ATLMessageInputToolbar.m
Fixes #1426 
Added ```safeAreaInsets.bottom``` to the ```ATLMessageInputToolbar``` height and subviews during layout so it's not overlapped on iPhone X.
=> Fixed ATLMessageInputToolbar layout according to safe area insets

Code/Controllers/ATLConversationViewController.m, Code/Models/ATLConversationDataSource.h, Code/Models/ATLConversationDataSource.m, Examples/Mocks/LYRQueryControllerMock.h, Examples/Mocks/LYRQueryControllerMock.m, fastlane/Scanfile
Fixes #1230 and fixes #1164
```ATLConversationDataSource``` keeps a copy of messages for presentation in ```ATLConversationViewController```, so whenever ```reloadData``` is called, it uses a shapshot of messages set, instead of all messages currently held by query controller. The copy of messages in ```ATLConversationDataSource``` is updated only during ```performBatchUpdates``` inside ```queryControllerDidChangeContent:``` delegate method, and that prevents the crash.
=> Fixed crash in converstaion view controller

Code/Views/ATLAvatarView.m
Changes:
* fix for #1431 (ATLAvatarView's imageViewBackgroundColor sets backgroundColor, not image view's background color);
=> #1431: fixed ATLAvatarView's imageViewBackgroundColor handling

Code/Controllers/ATLConversationListViewController.h, Code/Controllers/ATLConversationListViewController.m
This PR allows for clients who leverage Atlas to update the predicate that [`ATLConversationListViewController`](https://github.com/layerhq/Atlas-iOS/blob/master/Code/Controllers/ATLConversationListViewController.h) uses to populate itself.
I added a new method, [`updatePredicate:`](https://github.com/Snagajob/Atlas-iOS/commit/52e8fd2ba8c781f74a45093eb038564b7782bbc8#diff-4f587823069094564d475f3c2be66523R291), which allows for the `LYRPredicate` to be updated. This method simply calls the private [`updateQueryControllerWithPredicate `](https://github.com/layerhq/Atlas-iOS/blob/master/Code/Controllers/ATLConversationListViewController.m#L642-L649).
In our app, we have the following situation:
* A view loads `ATLConversationListViewController` with a subset of all available conversations
* …
=> Allow for Clients to Update the Conversation List Predicate

Atlas.xcodeproj/project.pbxproj, Atlas.xcodeproj/xcshareddata/xcschemes/Atlas-Carthage.xcscheme, circle.yml
I've added test Carthage build to CI, and it properly failed with:
```
carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/carthage-xcodebuild.lZSxBf.log
*** Cloning releases-ios
*** Building scheme "Atlas" in Atlas.xcworkspace
Build Failed
Task failed with exit code 65:
/usr/bin/xcrun xcodebuild -workspace /Users/distiller/Atlas-iOS/Atlas.xcworkspace -scheme Atlas -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath ./ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/distiller/Atlas-iOS)
This usually indicates that project itself failed to compile. Please …
```
=> [IOS-3310] Fixed carthage support

circle.yml
Carthage installation step was failing randomly, on workers that already had it installed.
=> Fixed installing carthage for tests in CircleCI
